### PR TITLE
Config update: Cloth Config API

### PR DESCRIPTION
**Pull request by TGODiamond**
This PR adds support for in-game configuration. The mod will now use Cloth Config API to handle configs. To access the settings, use the Mod Menu mod. Configuration without Mod Menu installed can still be done using the config file, which is now a json file.

Bumps mod version: (1.3.3 -> 1.4.0)
The mod will still work with both 1.20 and 1.20.1

## New features and changes:
- In-game configuration using Mod Menu.
- In-game configuration will take effect without needing to restart the game. Test this using F3 + T while in a world, or change resources packs.
- Translations to configuration are now supported.
- Updated the README.md file to show the dependencies.

## Dependency and tool updates:

Added Cloth Config API as a dependency (>=11.0.99)
Added Mod Menu as an optional dependency (>=7.0.1)

### CODE REVIEW

**Comment by TGODiamond** [comment]
My PR is ready to be merged

**Comment by trufflezmc** [comment]
Sorry for the delays; I'm looking over this implementation and would be happy to merge this, though adding dependencies is something I've been trying to avoid as it makes later versions break while users are notified and learn of the new requirements. Mod menu implementation though I am totally fine with. And feel free to add yourself as a contributor.

I understand that Cloth Config API is widely used and will probably be in a lot of modpacks, though for a mod as lightweight as this, I would prefer command-based config if it can avoid the new dependency.

For the larger mods going forward, extra dependencies are fine or even implementing my own menu API, we'll see.

**Comment by trufflezmc** [comment]
I'll try to figure out a way to hardcode your config implementation

**Comment by TGODiamond** [comment]
Cloth Config is a large dependency for sure. And Mod Menu supports implementing your own config GUI. I chose Cloth only for its ease of use and popularity. But the search feature isn't needed, and translations may be doable too if you choose so. Would be overall better if you find a lighter library, or hardcode it yourself.

**Comment by TGODiamond** [comment]
Closing this, as this project seems to be dead..

**Pull request closed without merging**
